// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: varint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type U32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         uint32                 `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *U32) Reset() {
	*x = U32{}
	mi := &file_varint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *U32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*U32) ProtoMessage() {}

func (x *U32) ProtoReflect() protoreflect.Message {
	mi := &file_varint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use U32.ProtoReflect.Descriptor instead.
func (*U32) Descriptor() ([]byte, []int) {
	return file_varint_proto_rawDescGZIP(), []int{0}
}

func (x *U32) GetField() uint32 {
	if x != nil {
		return x.Field
	}
	return 0
}

type U64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         uint64                 `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *U64) Reset() {
	*x = U64{}
	mi := &file_varint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *U64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*U64) ProtoMessage() {}

func (x *U64) ProtoReflect() protoreflect.Message {
	mi := &file_varint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use U64.ProtoReflect.Descriptor instead.
func (*U64) Descriptor() ([]byte, []int) {
	return file_varint_proto_rawDescGZIP(), []int{1}
}

func (x *U64) GetField() uint64 {
	if x != nil {
		return x.Field
	}
	return 0
}

type I32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         int32                  `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I32) Reset() {
	*x = I32{}
	mi := &file_varint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I32) ProtoMessage() {}

func (x *I32) ProtoReflect() protoreflect.Message {
	mi := &file_varint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I32.ProtoReflect.Descriptor instead.
func (*I32) Descriptor() ([]byte, []int) {
	return file_varint_proto_rawDescGZIP(), []int{2}
}

func (x *I32) GetField() int32 {
	if x != nil {
		return x.Field
	}
	return 0
}

type I64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         int64                  `protobuf:"varint,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I64) Reset() {
	*x = I64{}
	mi := &file_varint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I64) ProtoMessage() {}

func (x *I64) ProtoReflect() protoreflect.Message {
	mi := &file_varint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I64.ProtoReflect.Descriptor instead.
func (*I64) Descriptor() ([]byte, []int) {
	return file_varint_proto_rawDescGZIP(), []int{3}
}

func (x *I64) GetField() int64 {
	if x != nil {
		return x.Field
	}
	return 0
}

type S32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         int32                  `protobuf:"zigzag32,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S32) Reset() {
	*x = S32{}
	mi := &file_varint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S32) ProtoMessage() {}

func (x *S32) ProtoReflect() protoreflect.Message {
	mi := &file_varint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S32.ProtoReflect.Descriptor instead.
func (*S32) Descriptor() ([]byte, []int) {
	return file_varint_proto_rawDescGZIP(), []int{4}
}

func (x *S32) GetField() int32 {
	if x != nil {
		return x.Field
	}
	return 0
}

type S64 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         int64                  `protobuf:"zigzag64,1,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S64) Reset() {
	*x = S64{}
	mi := &file_varint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S64) ProtoMessage() {}

func (x *S64) ProtoReflect() protoreflect.Message {
	mi := &file_varint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S64.ProtoReflect.Descriptor instead.
func (*S64) Descriptor() ([]byte, []int) {
	return file_varint_proto_rawDescGZIP(), []int{5}
}

func (x *S64) GetField() int64 {
	if x != nil {
		return x.Field
	}
	return 0
}

var File_varint_proto protoreflect.FileDescriptor

const file_varint_proto_rawDesc = "" +
	"\n" +
	"\fvarint.proto\"\x1b\n" +
	"\x03u32\x12\x14\n" +
	"\x05field\x18\x01 \x01(\rR\x05field\"\x1b\n" +
	"\x03u64\x12\x14\n" +
	"\x05field\x18\x01 \x01(\x04R\x05field\"\x1b\n" +
	"\x03i32\x12\x14\n" +
	"\x05field\x18\x01 \x01(\x05R\x05field\"\x1b\n" +
	"\x03i64\x12\x14\n" +
	"\x05field\x18\x01 \x01(\x03R\x05field\"\x1b\n" +
	"\x03s32\x12\x14\n" +
	"\x05field\x18\x01 \x01(\x11R\x05field\"\x1b\n" +
	"\x03s64\x12\x14\n" +
	"\x05field\x18\x01 \x01(\x12R\x05fieldB\tZ\a./protob\x06proto3"

var (
	file_varint_proto_rawDescOnce sync.Once
	file_varint_proto_rawDescData []byte
)

func file_varint_proto_rawDescGZIP() []byte {
	file_varint_proto_rawDescOnce.Do(func() {
		file_varint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_varint_proto_rawDesc), len(file_varint_proto_rawDesc)))
	})
	return file_varint_proto_rawDescData
}

var file_varint_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_varint_proto_goTypes = []any{
	(*U32)(nil), // 0: u32
	(*U64)(nil), // 1: u64
	(*I32)(nil), // 2: i32
	(*I64)(nil), // 3: i64
	(*S32)(nil), // 4: s32
	(*S64)(nil), // 5: s64
}
var file_varint_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_varint_proto_init() }
func file_varint_proto_init() {
	if File_varint_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_varint_proto_rawDesc), len(file_varint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_varint_proto_goTypes,
		DependencyIndexes: file_varint_proto_depIdxs,
		MessageInfos:      file_varint_proto_msgTypes,
	}.Build()
	File_varint_proto = out.File
	file_varint_proto_goTypes = nil
	file_varint_proto_depIdxs = nil
}
