name: Pollux CI

on:
  push:
    branches:
      - main 
  pull_request:
    
jobs:
  buil-pollux-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v32
      - run: nix build --version 
      - run: nix build
      - name: pollux 
        run: ./result/bin/pollux.exe
