name: Pollux Lean CI

on:
  push:
    branches:
      - main
    paths:
      - "**/*.lean"
  pull_request:

jobs:
  build-lean-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "lean/"

  build-lean-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "lean/"
