// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: recursive.proto

package Rec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hd            int32                  `protobuf:"varint,1,opt,name=hd,proto3" json:"hd,omitempty"`
	Tl            *Stream                `protobuf:"bytes,2,opt,name=tl,proto3" json:"tl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_recursive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_recursive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_recursive_proto_rawDescGZIP(), []int{0}
}

func (x *Stream) GetHd() int32 {
	if x != nil {
		return x.Hd
	}
	return 0
}

func (x *Stream) GetTl() *Stream {
	if x != nil {
		return x.Tl
	}
	return nil
}

var File_recursive_proto protoreflect.FileDescriptor

const file_recursive_proto_rawDesc = "" +
	"\n" +
	"\x0frecursive.proto\"1\n" +
	"\x06Stream\x12\x0e\n" +
	"\x02hd\x18\x01 \x01(\x05R\x02hd\x12\x17\n" +
	"\x02tl\x18\x02 \x01(\v2\a.StreamR\x02tlB\fZ\n" +
	"Pollux/Recb\x06proto3"

var (
	file_recursive_proto_rawDescOnce sync.Once
	file_recursive_proto_rawDescData []byte
)

func file_recursive_proto_rawDescGZIP() []byte {
	file_recursive_proto_rawDescOnce.Do(func() {
		file_recursive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recursive_proto_rawDesc), len(file_recursive_proto_rawDesc)))
	})
	return file_recursive_proto_rawDescData
}

var file_recursive_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_recursive_proto_goTypes = []any{
	(*Stream)(nil), // 0: Stream
}
var file_recursive_proto_depIdxs = []int32{
	0, // 0: Stream.tl:type_name -> Stream
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_recursive_proto_init() }
func file_recursive_proto_init() {
	if File_recursive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recursive_proto_rawDesc), len(file_recursive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recursive_proto_goTypes,
		DependencyIndexes: file_recursive_proto_depIdxs,
		MessageInfos:      file_recursive_proto_msgTypes,
	}.Build()
	File_recursive_proto = out.File
	file_recursive_proto_goTypes = nil
	file_recursive_proto_depIdxs = nil
}
